feign:
  client:
    config:
      jplaceholder:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

logging:
  level:
    org.ait.project.aitboilerplate.shared.openfeign: DEBUG


openfeign:
  url:
    jplaceholder: https://jsonplaceholder.typicode.com/

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/alto_biller_adapter
    username: postgres
    password: postgres


server:
  port: 8081
  servlet:
    context-path: /api
