spring:
  application:
    name: @project.name@
    description: @project.description@
    groupId: @project.groupId@
    artifactId: @project.artifactId@
    version: @project.version@
#  profiles:
#    active: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/boilerplates
    username: root
    password: 123098
  jpa:
    open-in-view: true
  flyway:
    baseline-on-migrate: true
    locations: classpath:/db/migration

feign:
  client:
    config:
      jplaceholder:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

logging:
  org:
    hibernate: false
  level:
    org.ait.project.aitboilerplate.shared.openfeign: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        Type:
          descriptor:
            sql:
              BasicBinder: TRACE
    root: info

openfeign:
  url:
    jplaceholder: https://jsonplaceholder.typicode.com/

server:
  port: 8081
  servlet:
    context-path: /api
