spring:
#  profiles:
#    active: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/boilerplates2
    username: postgres
    password: postgres

feign:
  client:
    config:
      jplaceholder:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

logging:
  level:
    org.ait.project.aitboilerplate.shared.openfeign: DEBUG


openfeign:
  url:
    jplaceholder: https://jsonplaceholder.typicode.com/

server:
  port: 8081
  servlet:
    context-path: /api
